### ISSUE TITLE
Update Token creator to use SQL database

### ISSUE THREAD

**Issue by sardap** [sardap/Capstone-2019-Data-Sharing#177]
What:
* Update the Token creator to use the SQL database broker table instend of the list of three names

**Comment by sardap** [comment]
SQL DB branch https://github.com/sardap/Capstone-2019-Data-Sharing/tree/issue-173-policy-gateway-db/src/BCC/BCCDB

**Comment by sardap** [comment]
Image can be found here before https://cloud.docker.com/u/capstonegroup30/repository/docker/capstonegroup30/bccdb

**Comment by sardap** [comment]
https://github.com/sardap/Capstone-2019-Data-Sharing/blob/BCC_policy_gateway/src/BCC/PolicyGateway/app/startup.py

**Comment by Davis-A** [comment]
That took much longer than expected.  I had to wrap my head around a few things i haven't done in a while.  With a few squirly asynchronous javascript issues to handle.

Also included is a docker-compose.yml file to quickly set up the service (and database) locally for testing.  All previous tests should work.  

Code is done and ready for an unofficial review.  No pull request yet due to needing to update the README with the new environment variables and setting up to test steps.

https://github.com/sardap/Capstone-2019-Data-Sharing/tree/update_token_creator_broker_sqldb_177
